services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-frontend-url.netlify.app

databases:
  - name: portfolio-db
    plan: free
    ipAllowList: []
